### ISSUE TITLE
References not present in Processsing 4.2 for Linux

### ISSUE THREAD

**Issue by shyimon** [processing/processing4#733]
## Description
When trying to open the Environment Help entry nothing happens and the console prints out the following:
`java.io.IOException: Failed to show URI:file:/home/shyimon/Documents/processing-4.2/modes/java/reference/../environment/index.html
	at java.desktop/sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:124)
	at java.desktop/sun.awt.X11.XDesktopPeer.browse(XDesktopPeer.java:108)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:533)
	at processing.awt.ShimAWT.openLink(ShimAWT.java:943)
	at processing.app.platform.DefaultPlatform.openURL(DefaultPlatform.java:238)
	at processing.app.platform.LinuxPlatform.openURL(LinuxPlatform.java:126)
	at processing.app.Platform.openURL(Platform.java:159)
	at processing.mode.android.AndroidEditor.showReference(AndroidEditor.java:373)
	at processing.mode.java.JavaEditor.lambda$buildHelpMenu$7(JavaEditor.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

## Steps to Reproduce
1. Open Processing
2. Help > Environment
3. See console for the error log

## Your Environment
Running Processing 4.2 on EndeavourOS
* Processing version: 4.2
* Operating System and OS version: EndeavourOS, arch 6.3.8

**Comment by shyimon** [comment]
Thanks, was not aware that the reference was downloadable separately!

**Comment by benfry** [comment]
Oh… this is a bug in Android Mode, which needs to use the new reference setup. When using Java Mode, it will open the online reference if the offline reference hasn't yet been downloaded. 

Moving to the Android Mode repository so it can get fixed.
